#!/bin/bash
# this requires executables besides JRE
# apktool,enjarify,jad, jadx
# Script designed and Tested on Android Tamer (https://androidtamer.com) 

echo "APK TO JAVA source code extraction script"
echo "This is a script created by Anant Shrivastava"
echo "http://anantshri.info"
echo "Designed and Tested on Android Tamer"
echo "This script will work on automating the work of extracting the source code out from the apk file"
if [[ $# -eq 0 || $1 == "--help" || $1 == "-help" ]]
	then
	echo ""
	echo "$0 APK_FILE_NAME DESTINATION"
	exit 
fi
echo "[*] Starting APK Decompile"
# JAR KEEP is a variable which allows you to keep jar file converted using dex2jar.
# 0 is off
# 1 is on
JAR_KEEP=1
APK_NAME=`basename "$1"`
c=`basename "$APK_NAME" .apk`
FULL_PTH=`readlink -f "$1"`
APK_DIR_PATH=`dirname "$FULL_PTH"`

if [[ $# -eq 2 ]]
then
	if [[ "$2" != /* ]]
	then
		# Relative path
		SRC_DIR="$PWD"/"$2"/"$APK_NAME""_src/"
	else
		SRC_DIR=$2"/"$APK_NAME"_src/"
	fi
else
	SRC_DIR="$PWD/$APK_NAME""_src/"
fi

if [[ "$c" == `basename "$APK_NAME"` ]]
then
	echo "[-] Only APK's allowed. Exiting."
	exit
fi

#Checks if the file exists.
if [ ! -f "$FULL_PTH" ]
then
        echo "[-] File not found. Exiting."
        exit
fi

echo "[*] Creating Output Directory"
mkdir -p "$SRC_DIR"

echo "[*] Extracting files via APKTool"
apktool decode -f "$APK_DIR_PATH/$APK_NAME" -o "$SRC_DIR"

echo "[*] Enjarify for decoding back to java classes."
mkdir -p "$SRC_DIR"jar
JAR_FILE="$SRC_DIR""/jar/""$c""_enjarify.jar"
enjarify -f "$APK_DIR_PATH""/$APK_NAME" -o  "$JAR_FILE"

echo "[*] Decompiling via JADX Decompiler"
cd "$SRC_DIR"/jar
mkdir -p ../src/jadx
jadx -d ../src/jadx "$SRC_DIR""/jar/""$c""_enjarify.jar"
jar -xf "$c""_enjarify.jar"

echo "[*] Source Extraction via JAD from class files"
jad -o -r -sjava -d../src/jad './**/*.class'

if [ $JAR_KEEP -eq 0 ]
then
  	echo "[*] Removing jar file." 
	rm -rf "$c""_enjarify.jar"
	cd ..
	rm -rf ./jar
fi 
ls -l "$SRC_DIR"
cd "$APK_DIR_PATH"
echo "[*] All Done"